# Generated by Django 5.2.5 on 2025-08-11 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHotelInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('business_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('business_email', models.EmailField(max_length=254)),
                ('targeted_area', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('event_venue', 'Event Venue'), ('cafe', 'Cafe/Coffee Shop'), ('resort', 'Resort'), ('conference_center', 'Conference Center'), ('other', 'Other')], max_length=50)),
                ('business_address', models.TextField(blank=True)),
                ('capacity', models.CharField(blank=True, help_text='Number of rooms/capacity', max_length=50)),
                ('monthly_requirement', models.CharField(blank=True, choices=[('1000-5000', '1,000 - 5,000 bottles'), ('5000-10000', '5,000 - 10,000 bottles'), ('10000-25000', '10,000 - 25,000 bottles'), ('25000+', '25,000+ bottles')], max_length=20)),
                ('current_supplier', models.CharField(blank=True, max_length=100)),
                ('preferred_contact', models.CharField(blank=True, choices=[('phone', 'Phone'), ('email', 'Email'), ('both', 'Both')], max_length=10)),
                ('best_time_to_contact', models.CharField(blank=True, choices=[('morning', 'Morning (9 AM - 12 PM)'), ('afternoon', 'Afternoon (12 PM - 4 PM)'), ('evening', 'Evening (4 PM - 7 PM)'), ('anytime', 'Anytime')], max_length=20)),
                ('special_requirements', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Business Hotel Inquiry',
                'verbose_name_plural': 'Business Hotel Inquiries',
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('interest', models.CharField(choices=[('water-lover', 'For Water Lovers - Earning Rewards'), ('smart-brand', 'For Smart Brands - Advertising'), ('growth-partner', 'For Growth Partners - Partnership'), ('general', 'General Inquiry'), ('support', 'Technical Support')], max_length=20)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
            },
        ),
        migrations.CreateModel(
            name='EarnWithUsInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('partnership_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('dealer', 'Dealer/Distributor'), ('retailer', 'Retailer'), ('wholesale', 'Wholesale Partner'), ('regional', 'Regional Partner'), ('other', 'Other')], max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('business_reg_number', models.CharField(blank=True, max_length=100)),
                ('years_in_business', models.CharField(blank=True, choices=[('new', 'New Business/Startup'), ('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5-10', '5-10 Years'), ('10+', '10+ Years')], max_length=10)),
                ('business_volume', models.CharField(blank=True, choices=[('small', 'Small Scale (Local)'), ('medium', 'Medium Scale (Regional)'), ('large', 'Large Scale (Multi-State)'), ('enterprise', 'Enterprise Level')], max_length=20)),
                ('service_areas', models.TextField(blank=True)),
                ('investment_capacity', models.CharField(blank=True, choices=[('100000-500000', '₹1,00,000 - ₹5,00,000'), ('500000-1000000', '₹5,00,000 - ₹10,00,000'), ('1000000-2500000', '₹10,00,000 - ₹25,00,000'), ('2500000+', '₹25,00,000+')], max_length=20)),
                ('target_revenue', models.CharField(blank=True, choices=[('50000-100000', '₹50,000 - ₹1,00,000'), ('100000-250000', '₹1,00,000 - ₹2,50,000'), ('250000-500000', '₹2,50,000 - ₹5,00,000'), ('500000+', '₹5,00,000+')], max_length=20)),
                ('existing_client_base', models.TextField(blank=True)),
                ('marketing_experience', models.TextField(blank=True)),
                ('why_partner', models.TextField(blank=True)),
                ('business_proposal', models.TextField(blank=True)),
                ('referral_source', models.CharField(blank=True, choices=[('website', 'Website'), ('social_media', 'Social Media'), ('referral', 'Friend/Business Referral'), ('advertisement', 'Advertisement'), ('event', 'Event/Exhibition'), ('other', 'Other')], max_length=20)),
            ],
            options={
                'verbose_name': 'Earn With Us Inquiry',
                'verbose_name_plural': 'Earn With Us Inquiries',
            },
        ),
        migrations.CreateModel(
            name='QRLandingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('how_found_us', models.CharField(blank=True, choices=[('qr_scan', 'QR Code Scan'), ('social_media', 'Social Media'), ('friend', 'Friend Referral'), ('other', 'Other')], max_length=50)),
            ],
            options={
                'verbose_name': 'QR Landing Inquiry',
                'verbose_name_plural': 'QR Landing Inquiries',
            },
        ),
        migrations.CreateModel(
            name='SmartBrandInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('business_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('targeted_area', models.CharField(max_length=200)),
                ('industry_type', models.CharField(choices=[('technology', 'Technology'), ('food_beverage', 'Food & Beverage'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('automotive', 'Automotive'), ('finance', 'Finance'), ('fashion', 'Fashion & Lifestyle'), ('travel', 'Travel & Tourism'), ('other', 'Other')], max_length=50)),
                ('budget_range', models.CharField(choices=[('50000-100000', '₹50,000 - ₹1,00,000'), ('100000-250000', '₹1,00,000 - ₹2,50,000'), ('250000-500000', '₹2,50,000 - ₹5,00,000'), ('500000-1000000', '₹5,00,000 - ₹10,00,000'), ('1000000+', '₹10,00,000+')], max_length=20)),
                ('website_url', models.URLField(blank=True)),
                ('company_description', models.TextField(blank=True)),
                ('campaign_duration', models.CharField(blank=True, choices=[('1month', '1 Month'), ('3months', '3 Months'), ('6months', '6 Months'), ('12months', '12 Months'), ('custom', 'Custom')], max_length=20)),
                ('target_audience', models.TextField(blank=True)),
                ('social_instagram', models.CharField(blank=True, max_length=100)),
                ('social_facebook', models.CharField(blank=True, max_length=100)),
                ('video_duration', models.CharField(blank=True, choices=[('20', '20 seconds'), ('30', '30 seconds')], max_length=5)),
                ('previous_campaigns', models.TextField(blank=True)),
                ('campaign_goals', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Smart Brand Inquiry',
                'verbose_name_plural': 'Smart Brand Inquiries',
            },
        ),
    ]
