# Generated by Django 5.2.5 on 2025-08-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesshotelinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Business Hotel Inquiry', 'verbose_name_plural': 'Business Hotel Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Inquiry', 'verbose_name_plural': 'Contact Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='earnwithusinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Earn With Us Inquiry', 'verbose_name_plural': 'Earn With Us Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='qrlandinginquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'QR Landing Inquiry', 'verbose_name_plural': 'QR Landing Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='smartbrandinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Smart Brand Inquiry', 'verbose_name_plural': 'Smart Brand Inquiries'},
        ),
        migrations.RemoveField(
            model_name='businesshotelinquiry',
            name='best_time_to_contact',
        ),
        migrations.RemoveField(
            model_name='businesshotelinquiry',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='businesshotelinquiry',
            name='current_supplier',
        ),
        migrations.RemoveField(
            model_name='businesshotelinquiry',
            name='is_contacted',
        ),
        migrations.RemoveField(
            model_name='businesshotelinquiry',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='businesshotelinquiry',
            name='preferred_contact',
        ),
        migrations.RemoveField(
            model_name='businesshotelinquiry',
            name='special_requirements',
        ),
        migrations.RemoveField(
            model_name='contactinquiry',
            name='is_contacted',
        ),
        migrations.RemoveField(
            model_name='contactinquiry',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='earnwithusinquiry',
            name='business_proposal',
        ),
        migrations.RemoveField(
            model_name='earnwithusinquiry',
            name='business_reg_number',
        ),
        migrations.RemoveField(
            model_name='earnwithusinquiry',
            name='business_volume',
        ),
        migrations.RemoveField(
            model_name='earnwithusinquiry',
            name='existing_client_base',
        ),
        migrations.RemoveField(
            model_name='earnwithusinquiry',
            name='investment_capacity',
        ),
        migrations.RemoveField(
            model_name='earnwithusinquiry',
            name='is_contacted',
        ),
        migrations.RemoveField(
            model_name='earnwithusinquiry',
            name='marketing_experience',
        ),
        migrations.RemoveField(
            model_name='earnwithusinquiry',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='earnwithusinquiry',
            name='target_revenue',
        ),
        migrations.RemoveField(
            model_name='earnwithusinquiry',
            name='why_partner',
        ),
        migrations.RemoveField(
            model_name='earnwithusinquiry',
            name='years_in_business',
        ),
        migrations.RemoveField(
            model_name='qrlandinginquiry',
            name='is_contacted',
        ),
        migrations.RemoveField(
            model_name='qrlandinginquiry',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='smartbrandinquiry',
            name='campaign_duration',
        ),
        migrations.RemoveField(
            model_name='smartbrandinquiry',
            name='campaign_goals',
        ),
        migrations.RemoveField(
            model_name='smartbrandinquiry',
            name='is_contacted',
        ),
        migrations.RemoveField(
            model_name='smartbrandinquiry',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='smartbrandinquiry',
            name='previous_campaigns',
        ),
        migrations.RemoveField(
            model_name='smartbrandinquiry',
            name='social_facebook',
        ),
        migrations.AlterField(
            model_name='businesshotelinquiry',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesshotelinquiry',
            name='monthly_requirement',
            field=models.CharField(blank=True, choices=[('1000-5000', '1,000 - 5,000 bottles'), ('5000-10000', '5,000 - 10,000 bottles'), ('10000-25000', '10,000 - 25,000 bottles'), ('25000+', '25,000+ bottles')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='interest',
            field=models.CharField(choices=[('water-lover', 'For Water Lovers - Earning Rewards'), ('smart-brand', 'For Smart Brands - Advertising'), ('growth-partner', 'For Growth Partners - Partnership'), ('general', 'General Inquiry'), ('support', 'Technical Support')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='earnwithusinquiry',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='earnwithusinquiry',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('social_media', 'Social Media'), ('referral', 'Friend/Business Referral'), ('advertisement', 'Advertisement'), ('event', 'Event/Exhibition'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='earnwithusinquiry',
            name='service_areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrlandinginquiry',
            name='how_found_us',
            field=models.CharField(blank=True, choices=[('qr_scan', 'QR Code Scan'), ('social_media', 'Social Media'), ('friend', 'Friend Referral'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='smartbrandinquiry',
            name='budget_range',
            field=models.CharField(choices=[('50000-100000', '₹50,000 - ₹1,00,000'), ('100000-250000', '₹1,00,000 - ₹2,50,000'), ('250000-500000', '₹2,50,000 - ₹5,00,000'), ('500000-1000000', '₹5,00,000 - ₹10,00,000'), ('1000000+', '₹10,00,000+')], max_length=50),
        ),
        migrations.AlterField(
            model_name='smartbrandinquiry',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smartbrandinquiry',
            name='social_instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smartbrandinquiry',
            name='target_audience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smartbrandinquiry',
            name='video_duration',
            field=models.CharField(blank=True, choices=[('20', '20 seconds'), ('30', '30 seconds')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='smartbrandinquiry',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='businesshotelinquiry',
            table='business_hotel_inquiries',
        ),
        migrations.AlterModelTable(
            name='contactinquiry',
            table='contact_inquiries',
        ),
        migrations.AlterModelTable(
            name='earnwithusinquiry',
            table='earn_with_us_inquiries',
        ),
        migrations.AlterModelTable(
            name='qrlandinginquiry',
            table='qr_landing_inquiries',
        ),
        migrations.AlterModelTable(
            name='smartbrandinquiry',
            table='smart_brand_inquiries',
        ),
    ]
